CREATE TABLE TB_USER(
	USER_NO     NUMBER CONSTRAINT TB_USER_PK PRIMARY KEY,
	USER_ID     VARCHAR2(30) NOT NULL,
	USER_PW     VARCHAR2(30) NOT NULL,
	USER_NAME   VARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT CURRENT_DATE
);

COMMENT ON COLUMN TB_USER.USER_NO     IS '사용자 번호';
COMMENT ON COLUMN TB_USER.USER_ID     IS '사용자 아이디';
COMMENT ON COLUMN TB_USER.USER_PW     IS '사용자 비밀번호';
COMMENT ON COLUMN TB_USER.USER_NAME   IS '사용자 이름';
COMMENT ON COLUMN TB_USER.ENROLL_DATE IS '사용자 가입일';


-- USER_NO 컬럼에 삽입될 시퀀스 생성
CREATE SEQUENCE SEQ_USER_NO NOCACHE;

-- 샘플 데이터 INSERT
INSERT INTO TB_USER 
VALUES(SEQ_USER_NO.NEXTVAL, 'user01', 'pass01', '유저일', DEFAULT );
INSERT INTO TB_USER 
VALUES(SEQ_USER_NO.NEXTVAL, 'user02', 'pass02', '유저이', DEFAULT );

SELECT EMP_ID 사번 , EMP_NAME 이름,  DECODE(substr (emp_no,8,'1' ), 1, 'M', 2, 'F' ) 성별 ,  salary 급여 , job_name 직급명, nvl (dept_title, '없음') 부서명
FROM EMPLOYEE JOIN job USING (job_code) left JOIN DEPARTMENT  ON (DEPARTMENT.DEPT_ID = EMPLOYEE.DEPT_CODE)  
WHERE (SALARY>3000000) AND (salary< 4000000) AND  DECODE(substr (emp_no,8,'1' ), 1, 'M', 2, 'F' )= 'M'
ORDER BY SALARY DESC;


SELECT * FROM EMPLOYEE;
SELECT * FROM job;
SELECT * FROM DEPARTMENT;


SELECT * FROM TB_USER;



COMMIT;