CREATE TABLE TB_MEMBER(
	MEMBER_NO     NUMBER CONSTRAINT TB_MEMBER_PK PRIMARY KEY,
	MEMBER_ID     VARCHAR2(30) NOT NULL UNIQUE,
	MEMBER_PW     VARCHAR2(30) NOT NULL,
	MEMBER_NAME   VARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT CURRENT_DATE
);

COMMENT ON COLUMN TB_MEMBER.MEMBER_NO     IS '멤버 번호';
COMMENT ON COLUMN TB_MEMBER.MEMBER_ID     IS '멤버 아이디';
COMMENT ON COLUMN TB_MEMBER.MEMBER_PW     IS '멤버 비밀번호';
COMMENT ON COLUMN TB_MEMBER.MEMBER_NAME   IS '멤버 이름';
COMMENT ON COLUMN TB_MEMBER.ENROLL_DATE IS '멤버 가입일';


-- MEMBER_NO 컬럼에 삽입될 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

-- 샘플 데이터 INSERT
INSERT INTO TB_MEMBER 
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'MEMBER01', 'pass01', '유저일', DEFAULT );
INSERT INTO TB_MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'MEMBER02', 'pass02', '유저이', DEFAULT );

SELECT * FROM TB_MEMBER;

COMMIT;


CREATE TABLE TB_TODO(
	TODO_NO     NUMBER CONSTRAINT TODO_PK PRIMARY KEY,
	TODO_TITLE    VARCHAR2(30) NOT NULL,
	TODO_COMPLETE     CHAR(1) DEFAULT 'N' CHECK (TODO_COMPLETE IN ('Y','N')),
	ENROLL_DATE DATE DEFAULT CURRENT_DATE
);

COMMENT ON COLUMN TB_TODO.TODO_NO      IS '할일 번호';
COMMENT ON COLUMN TB_TODO.TODO_TITLE    IS '할일 제목';
COMMENT ON COLUMN TB_TODO.TODO_COMPLETE    IS '완료여부';
COMMENT ON COLUMN TB_TODO.ENROLL_DATE  IS '등록날짜';


-- TODO_NO 컬럼에 삽입될 시퀀스 생성
CREATE SEQUENCE SEQ_TODO_NO NOCACHE;

-- 샘플 데이터 INSERT
INSERT INTO TB_TODO 
VALUES(SEQ_TODO_NO.NEXTVAL, 'JDBC 복습하기', 'N', DEFAULT);

INSERT INTO TB_TODO 
VALUES(SEQ_TODO_NO.NEXTVAL, '운동하기', 'Y', DEFAULT);

SELECT * FROM TB_TODO;

COMMIT;

